---
engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      fatal:
        enabled: false
      Similar code:
        enabled: false
      Identical code:
        enabled: false
      import/no-unresolved:
        enabled: false
      duplication:
        enabled: true
    config:
      languages:
      - javascript
      extensions:
      - .es6
      - .js
      - .jsx
ratings:
  paths:
  - client/*.js
  - server/*.js
exclude_paths: []