const types = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  LOGIN_USER_RESPONSE: 'LOGIN_USER_RESPONSE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  ADD_FLASH_MESSAGE: 'ADD_FLASH_MESSAGE',
  DELETE_FLASH_MESSAGE: 'DELETE_FLASH_MESSAGE',
};

export default types;
