const types = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  LOGIN_USER_RESPONSE: 'LOGIN_USER_RESPONSE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  ADD_FLASH_MESSAGE: 'ADD_FLASH_MESSAGE',
  DELETE_FLASH_MESSAGE: 'DELETE_FLASH_MESSAGE',

  SIGNUP_USER_RESPONSE: 'SIGNUP_USER_RESPONSE',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_ERROR: 'SIGNUP_USER_ERROR',

  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

};

export default types;
